import type { BloqueHorario } from "@/types/horario";

export const HORARIOS_SEMANALES: BloqueHorario[] = [
  {
    id: "lun-0800",
    dia: "Lunes",
    hora: "08:00-09:30",
    clase: "Fuerza",
    instructor: "Equipo Coral",
    nivel: "Mixto",
  },
  {
    id: "lun-1000",
    dia: "Lunes",
    hora: "10:00-11:30",
    clase: "Fuerza",
    instructor: "Equipo Coral",
    nivel: "Mixto",
  },
  {
    id: "lun-1830",
    dia: "Lunes",
    hora: "18:30-19:30",
    clase: "Juveniles",
    instructor: "Equipo Coral",
    nivel: "Inicial",
  },
  {
    id: "lun-1930",
    dia: "Lunes",
    hora: "19:30-21:00",
    clase: "Jiu Jitsu No Gi",
    instructor: "Equipo Coral",
    nivel: "Avanzado",
  },
  {
    id: "mar-0830",
    dia: "Martes",
    hora: "08:30-09:30",
    clase: "Funcional",
    instructor: "Equipo Coral",
    nivel: "Mixto",
  },
  {
    id: "mar-0930",
    dia: "Martes",
    hora: "09:30-11:00",
    clase: "Jiu Jitsu Gi",
    instructor: "Equipo Coral",
    nivel: "Intermedio",
  },
  {
    id: "mar-1830",
    dia: "Martes",
    hora: "18:30-19:30",
    clase: "Infantiles",
    instructor: "Equipo Coral",
    nivel: "Inicial",
  },
  {
    id: "mar-1930",
    dia: "Martes",
    hora: "19:30-21:00",
    clase: "Jiu Jitsu Gi",
    instructor: "Equipo Coral",
    nivel: "Intermedio",
  },
  {
    id: "mie-0800",
    dia: "Miércoles",
    hora: "08:00-09:30",
    clase: "Fuerza",
    instructor: "Equipo Coral",
    nivel: "Mixto",
  },
  {
    id: "mie-1000",
    dia: "Miércoles",
    hora: "10:00-11:30",
    clase: "Fuerza",
    instructor: "Equipo Coral",
    nivel: "Mixto",
  },
  {
    id: "mie-1830",
    dia: "Miércoles",
    hora: "18:30-19:30",
    clase: "Juveniles",
    instructor: "Equipo Coral",
    nivel: "Inicial",
  },
  {
    id: "mie-1930",
    dia: "Miércoles",
    hora: "19:30-21:00",
    clase: "Jiu Jitsu No Gi",
    instructor: "Equipo Coral",
    nivel: "Avanzado",
  },
  {
    id: "jue-0830",
    dia: "Jueves",
    hora: "08:30-09:30",
    clase: "Funcional",
    instructor: "Equipo Coral",
    nivel: "Mixto",
  },
  {
    id: "jue-0930",
    dia: "Jueves",
    hora: "09:30-11:00",
    clase: "Jiu Jitsu Gi",
    instructor: "Equipo Coral",
    nivel: "Intermedio",
  },
  {
    id: "jue-1830",
    dia: "Jueves",
    hora: "18:30-19:30",
    clase: "Infantiles",
    instructor: "Equipo Coral",
    nivel: "Inicial",
  },
  {
    id: "jue-1930",
    dia: "Jueves",
    hora: "19:30-21:00",
    clase: "Jiu Jitsu Gi",
    instructor: "Equipo Coral",
    nivel: "Intermedio",
  },
  {
    id: "vie-0800",
    dia: "Viernes",
    hora: "08:00-09:30",
    clase: "Fuerza",
    instructor: "Equipo Coral",
    nivel: "Mixto",
  },
  {
    id: "vie-1000",
    dia: "Viernes",
    hora: "10:00-11:30",
    clase: "Fuerza",
    instructor: "Equipo Coral",
    nivel: "Mixto",
  },
  {
    id: "vie-1730",
    dia: "Viernes",
    hora: "17:30-18:30",
    clase: "Calaveritas",
    instructor: "Equipo Coral",
    nivel: "Inicial",
  },
  {
    id: "sab-0830",
    dia: "Sábado",
    hora: "08:30-09:30",
    clase: "Funcional",
    instructor: "Equipo Coral",
    nivel: "Mixto",
  },
  {
    id: "sab-0930",
    dia: "Sábado",
    hora: "09:30-11:00",
    clase: "Jiu Jitsu Gi",
    instructor: "Equipo Coral",
    nivel: "Intermedio",
  },
  {
    id: "sab-1930",
    dia: "Sábado",
    hora: "19:30-21:00",
    clase: "Jiu Jitsu Gi",
    instructor: "Equipo Coral",
    nivel: "Intermedio",
  },
];
